# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-02 13:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='city',
        ),
        migrations.DeleteModel(
            name='state',
        ),
    ]
